---
output:
  pdf_document: default
  html_document: default
---
# Introducción al lenguaje R {#intro}

## ¿Que es R?
R o The R Project for Statistical Computing [@R-base] es un lenguaje y entorno de programación de alto nivel, orientado a objetos y fundamentalmente centrado al análisis estadístico y gráfico, distribuido bajo la licencia GNU GPL y está disponible para los sistemas operativos Windows, Macintosh, Unix y GNU/Linux.

El origen de R se remonta a 1993 cuando Robert Gentleman y Ross Ihaka del Departamento de Estadística de la Universidad de Auckland adaptan el [lenguaje de programación S](https://en.wikipedia.org/wiki/S_(programming_language)), propio de los famosos Bell Laboratories de AT&T, el cual es un sistema para el análisis de datos desarrollado por John Chambers y Rick Becker fundamentalmente y usado desde finales de 1970 (Ross y Robert comienzan a llamar “R” al lenguaje que implementaron, por las iniciales de sus nombres). Es más, muchos de los libros y manuales sobre S son útiles para R. 

## ¿Por qué usar R?
R tiene varias ventajas respecto a otros lenguajes de programación de fines estadísticos o softwares dedicados. Entre otras podemos citar:

* Sus posibilidades gráficas son excelentes y muy versátiles. Esto llega hasta el punto de que muchos que R tiene dos aspectos: el de software, vamos a llamarlo, analítico y el gráfico, pudiendo incluso independizarse su aprendizaje.
* Cuenta con una elevada flexibilidad. Los trabajos más sencillos o complejos algoritmos pueden ejecutarse escribiéndose una palabra.
* No es “una caja negra” y en todo momento sabemos que estamos haciendo. Este es un aspecto que no se valora como se debería cuando hacemos nuestros análisis estadísticos: a costa de la facilidad de hacer todo con un par de clicks perdemos fácilmente el control de lo que estamos haciendo (o incluso llegamos a desconocerlo), algo que no debería ser permitido, ya que quien hace un análisis busca una conclusión y no saber cómo se obtiene debería invalidar por si solo dicha conclusión.
* En R, un análisis estadístico se realiza por pasos que arrojan resultados que se van almacenando en objetos. De esta forma, estos pueden recuperarse y usarse en cualquier momento.
* Al contrario que otros software, permite salidas mínimas de resultados, fácilmente legibles y analizables, y no una salida copiosa de datos y gráficos.
* Salvo que utilicemos una GUI, su aspecto es minimalista y espartano a conciencia (hasta su web sigue esta filosofía), siguiendo la filosofía de no perder el foco de atención de lo que estamos haciendo con el “marco” en el que lo hacemos.
* Es libre, con filosofía y objetivos del proyecto GNU, con lo que podemos acceder al código escrito por otros usuarios y modificarlo libremente y evidentemente, podemos programar nuestras propios procedimientos y aplicaciones.
* Es un proyecto vivo con dos millones de usuarios. Seguramente a nuestro problema ya se habrá enfrentado alguien y casi con total seguridad no deberemos avanzar más de “tres páginas de Google” para encontrar la solución.
* Existen multitud de librerías (paquetes) programadas por los usuarios de todo el mundo para llevar a cabo procedimientos específicos (¡más de 10.000!).
* Y si con todo ello, no tenemos suficiente, es totalmente gratuito, tanto el como todo su ecosistema.

## Recursos sobre R
Para aprender sobre R y estar al corriente de las últimas novedades existen una serie de recursos que deberemos añadir a nuestros Favoritos. Entre otros:

* Página oficial de R: [https://www.r-project.org/](https://www.r-project.org/)
* Fundación R: [https://www.r-project.org/foundation/](https://www.r-project.org/foundation)
* Manuales iniciales: [https://cran.r-project.org/manuals.html](https://cran.r-project.org/manuals.html)
* Revista R: [https://journal.r-project.org/](https://journal.r-project.org/)
* R-Bloggers: [http://www.r-bloggers.com/](http://www.r-bloggers.com/)
* Comunidad R-Hispano: [http://r-es.org/Comunidad](http://r-es.org/Comunidad)
* Recursos MOOC como Coursera: [www.coursera.org](www.coursera.org)
* Bibliografía en papel: "R for Everyone: Advanced Analytics and Graphics" ([http://www.jaredlander.com/r-for-everyone/](http://www.jaredlander.com/r-for-everyone/)), "R Cookbook" ([http://shop.oreilly.com/product/9780596809164.do](http://shop.oreilly.com/product/9780596809164.do)) y el clásico "Modern Applied Statistics with S" ([http://www.springer.com/us/book/9780387954578](http://www.springer.com/us/book/9780387954578))