# Sobre el autor {#about}


Mi nombre es Julio M. Sevilla y soy Ingeniero Forestal por la Universidad de Huelva con formación de postgrado en Métodos Avanzados de Estadística Aplicada y Máster en Técnicas Actuales de Estadística Aplicada. A raíz de iniciar mi vida profesional en el área de la investigación, comienzo a apasionarme por la Estadística Aplicada y los Sistemas de Información Geográfica, especializándome en técnicas de muestreo, análisis espacial mediante Sistemas de Información Geográfica y modelización estadística. En los últimos años mi formación va encaminada por las emergentes técnicas de aprendizaje automático estadístico orientadas al análisis espacial, la teledetección, geoestadística y LiDAR. Asimismo, complemento esta formación con preparación en gestión y administración de empresas, inteligencia de negocio y gestión y valoración de proyectos. Por otro lado, soy autor y co-autor de varias publicaciones científicas.

Si quieres saber más, puedes ponerte en contacto a traves del mail y las redes sociales:

- [epidom.es](https://www.epidom.es)
- [jmsevilla@epidom.es](jmsevilla@epidom.es)
- [Linkedin](https://es.linkedin.com/in/juliomsevilla)




